---

global:
  sendAnonymousUsage: false
  
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

certificatesResolvers:
  le:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # Change this to the non-staging URL once you have a working configuration.
      storage: "/etc/traefik/acme/acme.json"
      dnsChallenge:
        provider: "duckdns"

      
