---
- name: Allow port 80
  ansible.posix.firewalld:
    port: "80/tcp"
    permanent: true
    state: enabled

- name: Allow port 443
  ansible.posix.firewalld:
    port: "443/tcp"
    permanent: true
    state: enabled