---
- name: Ensure the user for rootless podman is created
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512')}}"
    groups:
      - users
    append: yes
    shell: /bin/bash
    update_password: on_create

- name: Enable passwordless sudo for me
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "micah ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

