---
- name: Deploy AdGuard Home
  become: false
  containers.podman.podman_container:
    name: agh
    image: docker.io/adguard/adguardhome
    volumes:
      #- "agh-workdir:/opt/adguardhome/work:z"
      - "{{ container_dir }}/adguard-home/work:/opt/adguardhome/work:z"
      #- "agh-confdir:/opt/adguardhome/conf:z"
      - "{{ container_dir }}/adguard-home/conf:/opt/adguardhome/conf:z"
    ports:
      - '8081:80'
      - '3000:3000/tcp'
      - '53:53/tcp'
      - '53:53/udp'
      - '853:853/tcp'
      - '853:853/udp'
      - '5443:5443/tcp'
      - '5443:5443/udp'
      - '6060:6060/tcp'

