---

- name: Ensure proper container directories are present.
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    setype: container_file_t
  become_user: "{{ username }}"
  become: true
  loop:
    - "{{ container_compose }}"
    #- "{{ container_dir }}/traefik/acme"
    - "{{ container_dir }}/nginx"
    - "{{ container_dir }}/letsencrypt"
    #- "{{ container_dir }}/pihole/etc-pihole"
    - "{{ container_dir }}/pihole/etc-dnsmasq.d"

#- name: Create a podman network for reverse-proxied network services 
#  containers.podman.podman_network:
#    name: nginx-net
#  become: false

- name: Deploy Nginx Proxy manager
  become: false
  containers.podman.podman_container:
    name: nginx
    image: docker.io/jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - "{{ container_dir }}/nginx:/data:Z"
      - "{{ container_dir }}/letsencrypt:/etc/letsencrypt:Z"

- name: Deploy Pi-hole with traefik labels
  become: false
  containers.podman.podman_container:
    name: pihole 
    image: docker.io/pihole/pihole:latest
    volumes:
      - "{{ container_dir }}/pihole/etc-pihole:/etc/pihole/:Z"
      - "{{ container_dir }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/:z"
    ports:
      - "53:53"
      - "853:853"
      - "8081:80"


    


