---
- name: Set up Vaultwarden
  become: false
  containers.podman.podman_container:
    name: vw 
    image: docker.io/vaultwarden/server:latest
    volumes:
      - "{{ container_dir }}/vw-vault/data:/data:Z"
    ports:
      - "8082:80"

- name: Create systemd service
  containers.podman.podman_generate_systemd:
    name: vw
    new: true
    dest: ~/.config/systemd/user

- name: Enable systemd service
  systemd:
    name: container-vw.service
    enabled: true
    scope: user